export const SEED_ARTICLES = [
  {
    title: 'Como o ciclo menstrual afeta seu treino',
    summary: 'Entenda as 4 fases do ciclo e como adaptar seu treino para cada uma delas.',
    body: `## O ciclo menstrual e o treino\n\nO ciclo menstrual dura em media 28 dias e e dividido em 4 fases...\n\n### Fase Menstrual (dias 1-5)\nNesta fase, os niveis de estrogeno e progesterona estao baixos. Voce pode sentir fadiga e colicas. **Recomendacao**: exercicios leves como yoga, caminhada e alongamento.\n\n### Fase Folicular (dias 6-12)\nO estrogeno comeca a subir. Energia e disposicao aumentam. **Recomendacao**: treinos de forca progressiva, HIIT, cardio intenso. E a melhor fase para bater recordes!\n\n### Fase Ovulatoria (dias 13-15)\nPico de estrogeno. Energia maxima. **Recomendacao**: performance maxima, treinos pesados. **Atencao**: risco ligamentar aumentado pela relaxina.\n\n### Fase Lutea (dias 16-28)\nProgesterona sobe, estrogeno cai. Fadiga e alteracao de humor. **Recomendacao**: pilates, treino moderado, mobilidade.\n\n### Referencia\nMcNulty KL et al. The Effects of Menstrual Cycle Phase on Exercise Performance. Sports Medicine. 2020;50(10):1813-1827.`,
    categorySlug: 'ciclo',
    cyclePhase: 'all',
  },
  {
    title: 'Proteina e ciclo menstrual: quanto consumir em cada fase',
    summary: 'A demanda proteica varia ao longo do ciclo. Saiba ajustar sua dieta.',
    body: '## Proteina por fase do ciclo\n\nA International Society of Sports Nutrition recomenda 1.4-2.0g de proteina por kg de peso corporal para mulheres ativas.\n\n### Fase folicular\nConsumo padrao: 1.4g/kg. Foco em fontes completas (ovos, frango, peixe, whey).\n\n### Fase lutea\nAumente para 1.6-1.8g/kg. A progesterona aumenta o catabolismo proteico.\n\n### Referencia\nJager R et al. ISSN Position Stand: protein and exercise. J Int Soc Sports Nutr. 2017;14:20.',
    categorySlug: 'nutricao',
    cyclePhase: 'all',
  },
  {
    title: 'HIIT na fase folicular: por que e o momento ideal',
    summary: 'A ciencia explica por que a fase folicular e perfeita para treinos intensos.',
    body: '## HIIT e a fase folicular\n\nEstudos mostram que a fase folicular (dias 6-12) e o periodo de maior capacidade para exercicios de alta intensidade.\n\n### Evidencia cientifica\nUm estudo com 18 atletas eumenorreicas demonstrou que a forca dinamica maxima no half-squat atingiu seu pico na fase folicular tardia e na ovulacao.\n\n### Protocolo sugerido\n- 4-6 intervalos de 30s a 90% FCmax\n- 60-90s de recuperacao\n- 2-3 sessoes por semana nesta fase\n\n### Referencia\nWen Y et al. Exercise performance at different phases of the menstrual cycle. Front Endocrinol. 2025;16:1448686.',
    categorySlug: 'treino',
    cyclePhase: 'follicular',
  },
  {
    title: 'Alimentos anti-inflamatorios para a TPM',
    summary: 'Reduza sintomas pre-menstruais com alimentacao estrategica.',
    body: '## Combatendo a TPM com alimentacao\n\n### Alimentos recomendados\n- **Omega-3**: salmao, sardinha, chia, linhaca\n- **Magnesio**: chocolate amargo 70%+, castanhas, espinafre\n- **Vitamina B6**: banana, batata doce, frango\n- **Calcio**: iogurte natural, brocolis\n\n### Alimentos a evitar\n- Excesso de sodio (inchaço)\n- Cafeina em excesso (ansiedade)\n- Acucar refinado (oscilacao de humor)\n\n### Referencia\nGuia Alimentar para a Populacao Brasileira. MS, 2014.',
    categorySlug: 'nutricao',
    cyclePhase: 'luteal',
  },
  {
    title: 'Treino de forca e saude ossea na menopausa',
    summary: 'Como o exercicio resistido previne osteoporose apos a menopausa.',
    body: '## Forca e ossos\n\nApos a menopausa, a queda de estrogeno acelera a perda de massa ossea. O treino de forca e a intervencao mais eficaz para prevencao.\n\n### Protocolo recomendado\n- 2-3 sessoes/semana de treino resistido\n- Foco em exercicios de carga axial (agachamento, terra)\n- Progressao gradual de carga\n- Incluir exercicios de equilibrio\n\n### Referencia\nACSM Position Stand on Exercise and Physical Activity for Older Adults.',
    categorySlug: 'treino',
    cyclePhase: 'all',
  },
  {
    title: 'Sono e recuperacao: o papel do ciclo hormonal',
    summary: 'Qualidade do sono varia ao longo do ciclo. Aprenda a otimizar.',
    body: '## Sono e hormonios\n\nA progesterona tem efeito sedativo natural, enquanto o estrogeno influencia a arquitetura do sono.\n\n### Fase folicular\nMenor progesterona = sono pode ser mais leve. Foco em higiene do sono.\n\n### Fase lutea\nProgesterona alta = sonolencia diurna possivel. Temperatura corporal basal sobe, dificultando o sono.\n\n### Dicas\n- Ambiente fresco (18-20C)\n- Evitar telas 1h antes\n- 7-9 horas por noite\n\n### Referencia\nEstudo com atletas: motivacao e qualidade do sono nao variaram significativamente entre fases (p = 0.424-0.698).',
    categorySlug: 'ciclo',
    cyclePhase: 'all',
  },
  {
    title: 'Ansiedade e exercicio: PHQ e GAD como ferramentas',
    summary: 'Como monitorar saude mental e usar exercicio como terapia.',
    body: '## Saude mental e movimento\n\nO exercicio regular reduz sintomas de ansiedade e depressao. Instrumentos como PHQ-9 e GAD-7 ajudam a monitorar.\n\n### Exercicio como intervencao\n- 150 min/semana de atividade moderada\n- Yoga e pilates para reducao de cortisol\n- Treino ao ar livre (exposicao solar)\n\n### Na fase lutea\nEstudos mostram aumento de fadiga e depressao no POMS durante a fase lutea tardia. Exercicios leves ajudam.\n\n### Referencia\nKroenke K et al. The PHQ-9. J Gen Intern Med. 2001.\nSpitzer RL et al. The GAD-7. Arch Intern Med. 2006.',
    categorySlug: 'ciclo',
    cyclePhase: 'luteal',
  },
  {
    title: 'Yoga restaurativa na fase menstrual',
    summary: 'Posturas suaves para aliviar colicas e acolher seu corpo.',
    body: '## Yoga na menstruacao\n\n### Posturas recomendadas\n- **Balasana** (postura da crianca): alivia dor lombar\n- **Supta Baddha Konasana** (borboleta deitada): abre quadril\n- **Viparita Karani** (pernas na parede): reduz inchaço\n- **Savasana** com bolster: relaxamento profundo\n\n### Evitar\n- Inversoes prolongadas\n- Posturas de compressao abdominal intensa\n\n### Duracao\n20-30 minutos, com respiracao diafragmatica.\n\n### Referencia\nSchlie J et al. 2025: pior performance percebida durante sangramento.',
    categorySlug: 'treino',
    cyclePhase: 'menstrual',
  },
  {
    title: 'Deficit calorico seguro: como calcular',
    summary: 'Aprenda a calcular seu deficit sem prejudicar a saude.',
    body: '## Calculando o deficit\n\n### Formula de Mifflin-St Jeor\nMulher: TMB = (10 x peso kg) + (6.25 x altura cm) - (5 x idade) - 161\n\n### TDEE\nTDEE = TMB x fator de atividade\n- Sedentaria: 1.2\n- Leve: 1.375\n- Moderada: 1.55\n- Ativa: 1.725\n\n### Deficit seguro\n- 500-750 kcal/dia\n- Nunca abaixo de 1200 kcal/dia\n- Perda esperada: 0.5-0.75 kg/semana\n\n### Referencia\nMifflin MD et al. Am J Clin Nutr. 1990.\nHall KD et al. Am J Clin Nutr. 2012.',
    categorySlug: 'nutricao',
    cyclePhase: 'all',
  },
  {
    title: 'Risco ligamentar na ovulacao: o que toda atleta deve saber',
    summary: 'Estrogeno alto aumenta laxidez ligamentar. Saiba se proteger.',
    body: '## Ligamentos e hormonios\n\nDurante a ovulacao, o pico de estrogeno aumenta a producao de relaxina, que pode aumentar a laxidez ligamentar.\n\n### Risco\n- LCA (ligamento cruzado anterior) e o mais vulneravel\n- Incidencia de lesao de LCA em mulheres: 2-8x maior que em homens\n- Maior risco nos dias 10-14 do ciclo\n\n### Prevencao\n- Aquecimento prolongado (15 min)\n- Exercicios neuromusculares de estabilizacao\n- Fortalecimento de isquiotibiais\n- Evitar superficies irregulares\n\n### Referencia\nEstudo com 18 atletas: performance maxima na ovulacao, mas risco ligamentar aumentado.',
    categorySlug: 'ciclo',
    cyclePhase: 'ovulatory',
  },
  {
    title: 'SOP/PCOS e exercicio: como o treino ajuda a equilibrar hormonios',
    summary: 'A Sindrome dos Ovarios Policisticos afeta ate 15% das mulheres. O exercicio e uma das melhores intervencoes nao-farmacologicas.',
    body: `## SOP/PCOS e exercicio\n\nA Sindrome dos Ovarios Policisticos (SOP ou PCOS) e um disturbio endocrino que afeta entre 6% e 15% das mulheres em idade reprodutiva. Caracteriza-se por hiperandrogenismo, irregularidade menstrual e cistos ovarianos. A resistencia a insulina e um componente central da condicao.\n\n### Como o exercicio ajuda\n- **Melhora a sensibilidade a insulina**: treino de forca e aerobico melhoram a captacao de glicose em ate 30%\n- **Reduz testosterona livre**: exercicio regular diminui androgenios circulantes\n- **Regula o ciclo**: mulheres com SOP que se exercitam regularmente relatam ciclos mais regulares\n- **Reduz inflamacao cronica**: biomarcadores inflamatorios como PCR diminuem com exercicio\n\n### Protocolo recomendado\n- **Treino de forca**: 3x/semana, foco em grandes grupos musculares (agachamento, levantamento terra, supino)\n- **Cardio moderado**: 150 min/semana de caminhada rapida, natacao ou ciclismo\n- **Evitar overtraining**: cortisol elevado piora a SOP\n- **HIIT com moderacao**: 1-2 sessoes/semana, nao mais\n\n### Alimentacao complementar\n- Priorizar alimentos de baixo indice glicemico\n- Incluir fibras em todas as refeicoes\n- Omega-3 para reducao de inflamacao\n- Inositol como suplemento potencial (consulte seu medico)\n\n### Referencia\nTeede HJ et al. Recommendations from the international evidence-based guideline for the assessment and management of polycystic ovary syndrome. Hum Reprod. 2018;33(9):1602-1618.`,
    categorySlug: 'saude-mental',
    cyclePhase: 'all',
  },
  {
    title: 'Assoalho pelvico: exercicios essenciais para toda mulher',
    summary: 'Um assoalho pelvico forte previne incontinencia, melhora a postura e potencializa o treino de forca.',
    body: `## Assoalho pelvico: guia completo\n\nO assoalho pelvico e um conjunto de musculos que sustenta orgaos como bexiga, utero e reto. Sua fraqueza esta associada a incontinencia urinaria, prolapso e disfuncao sexual. Estima-se que 1 em cada 3 mulheres sofra algum grau de disfuncao do assoalho pelvico ao longo da vida.\n\n### Por que fortalecer\n- **Prevencao de incontinencia**: especialmente apos gravidez e na menopausa\n- **Melhor estabilidade do core**: o assoalho pelvico e parte do cilindro de estabilizacao junto com diafragma, transverso do abdomen e multifidos\n- **Performance no treino**: um assoalho pelvico funcional melhora a transmissao de forca em agachamentos e levantamentos\n- **Saude sexual**: melhora sensibilidade e controle\n\n### Exercicios essenciais\n- **Kegel classico**: contraia os musculos como se fosse interromper o fluxo urinario. Segure 5-10s, relaxe 10s. 3 series de 10 repeticoes\n- **Bridge com ativacao pelvica**: ponte de gluteo contraindo o assoalho pelvico na subida\n- **Deep squat hold**: agachamento profundo com foco na liberacao do assoalho pelvico (30-60s)\n- **Bird dog com ativacao**: quatro apoios, estender braco e perna opostos ativando o assoalho pelvico\n- **Respiracao diafragmatica**: inspirar expandindo o abdomen, expirar ativando suavemente o assoalho pelvico\n\n### Cuidados\n- Nao contrair gluteos ou abdomen durante Kegels isolados\n- Evitar prender a respiracao\n- Se sentir dor, procure um fisioterapeuta pelvico\n\n### Referencia\nDumoulin C et al. Pelvic floor muscle training versus no treatment for urinary incontinence in women. Cochrane Database Syst Rev. 2018;10:CD005654.`,
    categorySlug: 'treino',
    cyclePhase: 'all',
  },
  {
    title: 'Hidratacao e performance feminina: quanto e como beber',
    summary: 'As necessidades hidricas da mulher variam com o ciclo menstrual. Saiba como manter-se hidratada para performance maxima.',
    body: `## Hidratacao e performance feminina\n\nA desidratacao de apenas 2% do peso corporal ja reduz a performance cognitiva e fisica. Mulheres tem particularidades hidricas importantes devido as flutuacoes hormonais ao longo do ciclo menstrual.\n\n### Necessidades por fase\n- **Fase folicular**: necessidade basal de 2.0-2.5L/dia. Estrogeno em ascensao favorece a retencao hidrica\n- **Ovulacao**: temperatura corporal comeca a subir, aumente 300-500ml/dia\n- **Fase lutea**: progesterona e um diuretico natural. A temperatura basal sobe 0.3-0.5C. Aumente para 2.5-3.0L/dia\n- **Menstrual**: perdas adicionais pela menstruacao. Manter pelo menos 2.5L/dia\n\n### Sinais de desidratacao\n- Urina escura (ideal: amarelo claro)\n- Fadiga inexplicavel\n- Dor de cabeca\n- Queda de rendimento no treino\n- Caimbras musculares\n\n### Estrategias praticas\n- Beba 500ml ao acordar\n- 200-300ml a cada 20 min durante o treino\n- Inclua eletrolitos em treinos acima de 60 min\n- Agua de coco como opcao natural de reposicao\n- Frutas com alto teor de agua: melancia, melao, laranja\n\n### Eletrolitos importantes\n- **Sodio**: 300-600mg/hora em exercicio intenso\n- **Potassio**: bananas, agua de coco\n- **Magnesio**: especialmente na fase lutea para reduzir caimbras\n\n### Referencia\nArmstrong LE et al. Mild dehydration affects mood in healthy young women. J Nutr. 2012;142(2):382-388.`,
    categorySlug: 'nutricao',
    cyclePhase: 'all',
  },
  {
    title: 'Carb cycling e ciclo menstrual: como alinhar carboidratos com seus hormonios',
    summary: 'Aprenda a periodizar carboidratos conforme cada fase do ciclo para maximizar energia e composicao corporal.',
    body: `## Carb cycling sincronizado com o ciclo\n\nCarb cycling e a estrategia de variar a ingestao de carboidratos conforme a demanda energetica. Quando sincronizado ao ciclo menstrual, potencializa resultados e minimiza desconforto.\n\n### Fase menstrual (dias 1-5)\n- **Carboidratos moderados**: 3-4g/kg/dia\n- Priorize carboidratos complexos: aveia, batata doce, arroz integral\n- Incluir alimentos ricos em ferro para repor perdas\n- Chocolate amargo 70%+ como fonte de magnesio e comfort food funcional\n\n### Fase folicular (dias 6-12)\n- **Carboidratos altos**: 4-6g/kg/dia\n- Estrogeno em ascensao melhora a sensibilidade a insulina\n- Melhor janela para usar carboidratos simples peri-treino\n- Ideal para treinos intensos com alta demanda glicogenica\n\n### Fase ovulatoria (dias 13-15)\n- **Carboidratos moderados-altos**: 4-5g/kg/dia\n- Manter energia para performance maxima\n- Incluir antioxidantes: frutas vermelhas, acai\n\n### Fase lutea (dias 16-28)\n- **Carboidratos mais baixos**: 2-3g/kg/dia na primeira metade, aumentando para 3-4g/kg na semana pre-menstrual\n- Resistencia a insulina aumenta com a progesterona\n- Priorize carboidratos de baixo IG\n- Na semana pre-menstrual, o corpo naturalmente pede mais carboidratos - atenda com fontes saudaveis\n\n### Dica pratica\nNao elimine carboidratos totalmente em nenhuma fase. O cerebro feminino e particularmente sensivel a restricao de carboidratos, podendo causar alteracoes de humor e compulsoes.\n\n### Referencia\nWise LA et al. Dietary intake and menstrual cycle function. Public Health Nutr. 2018;21(4):739-748. Sims ST, Heather AK. Myths and Methodologies: Reducing scientific design ambiguity in studies comparing sexes and/or menstrual cycle phases. Exp Physiol. 2018;103(10):1309-1317.`,
    categorySlug: 'nutricao',
    cyclePhase: 'all',
  },
  {
    title: 'Treino de forca na menopausa: guia completo',
    summary: 'O treino resistido e a principal ferramenta para preservar massa muscular, ossea e metabolismo na menopausa.',
    body: `## Treino de forca na menopausa\n\nA menopausa marca o fim dos ciclos menstruais e traz uma queda acentuada de estrogeno. Isso resulta em perda acelerada de massa muscular (sarcopenia), massa ossea (osteopenia/osteoporose) e aumento da gordura visceral. O treino de forca e a intervencao mais eficaz para combater esses efeitos.\n\n### Beneficios comprovados\n- **Massa ossea**: cargas mecanicas estimulam osteoblastos e previnem osteoporose\n- **Massa muscular**: previne perda de 3-8% por decada apos os 40\n- **Metabolismo**: cada kg de musculo queima 6-10 kcal/dia em repouso\n- **Saude cardiovascular**: reduz pressao arterial e melhora perfil lipidico\n- **Saude mental**: reduz sintomas de depressao e ansiedade\n- **Equilibrio**: previne quedas, principal causa de fraturas\n\n### Protocolo recomendado\n- **Frequencia**: 3-4x por semana\n- **Exercicios prioritarios**: agachamento, levantamento terra, supino, remada, desenvolvimento\n- **Repeticoes**: 6-12 reps com carga moderada-alta (70-85% 1RM)\n- **Progressao**: aumentar carga 2-5% a cada 2 semanas\n- **Impacto**: incluir exercicios com salto leve (step-ups, pular corda) para estimulo osseo\n\n### Cuidados especificos\n- Aquecimento prolongado (10-15 min) para articulacoes\n- Hidratacao extra (menopausa reduz a percepcao de sede)\n- Suplementar vitamina D e calcio conforme orientacao medica\n- Sono adequado (menopausa frequentemente causa insonia)\n\n### Referencia\nStojanovska L et al. To exercise, or, not to exercise, during menopause and beyond. Maturitas. 2014;77(4):318-323. Howe TE et al. Exercise for preventing and treating osteoporosis in postmenopausal women. Cochrane Database Syst Rev. 2011;(7):CD000333.`,
    categorySlug: 'treino',
    cyclePhase: 'all',
  },
  {
    title: 'Alongamento e mobilidade: guia por fase do ciclo menstrual',
    summary: 'A flexibilidade e a mobilidade articular mudam ao longo do ciclo. Adapte sua rotina para cada fase.',
    body: `## Alongamento e mobilidade por fase\n\nA flexibilidade nao e constante ao longo do ciclo menstrual. Hormonios como estrogeno e relaxina influenciam diretamente a elasticidade dos tecidos conjuntivos. Entender essas variacoes permite uma pratica mais segura e eficaz.\n\n### Fase menstrual (dias 1-5)\n- **Foco**: mobilidade suave e relaxamento\n- Alongamentos passivos com suporte (bolster, blocos)\n- Liberacao miofascial com rolo ou bola\n- Yin yoga: posturas mantidas por 3-5 minutos\n- Evitar alongamentos profundos forçados\n\n### Fase folicular (dias 6-12)\n- **Foco**: mobilidade dinamica e amplitude de movimento\n- Aquecimento articular completo antes do treino\n- Alongamento dinamico: balanceios de perna, circulos de quadril\n- Bom momento para trabalhar novas amplitudes\n- Progressao em flexibilidade (splits, pontes)\n\n### Fase ovulatoria (dias 13-15)\n- **Foco**: estabilidade antes de flexibilidade\n- **Atencao**: relaxina elevada aumenta laxidez ligamentar\n- Priorizar exercicios de estabilizacao articular\n- Evitar alongamentos ballisticos\n- Foam rolling para manutencao\n\n### Fase lutea (dias 16-28)\n- **Foco**: manutencao e relaxamento\n- Alongamentos suaves pos-treino\n- Mobilidade de quadril e coluna toracia\n- Respiracao integrada ao alongamento\n- Na semana pre-menstrual: restorative yoga\n\n### Rotina rapida (10 min)\n1. Cat-cow: 10 repeticoes\n2. World's greatest stretch: 5 cada lado\n3. 90/90 hip switch: 8 repeticoes\n4. Thoracic rotation: 8 cada lado\n5. Deep squat hold: 30 segundos\n\n### Referencia\nBell DR et al. Systematic review of the balance error scoring system. Sports Health. 2011;3(3):287-295. Wikstrom EA et al. Joint laxity and stiffness in the ankle. Med Sci Sports Exerc. 2006;38(4):702-708.`,
    categorySlug: 'treino',
    cyclePhase: 'all',
  },
  {
    title: 'Suplementacao feminina baseada em evidencias',
    summary: 'Quais suplementos realmente funcionam para a mulher ativa? Separamos ciencia de marketing.',
    body: `## Suplementacao feminina: o que a ciencia diz\n\nO mercado de suplementos e enorme, mas poucos tem evidencia solida. Aqui esta o que realmente funciona para mulheres ativas, baseado em meta-analises e revisoes sistematicas.\n\n### Suplementos com forte evidencia\n- **Creatina monohidratada (3-5g/dia)**: melhora forca, potencia e composicao corporal. Segura para mulheres. Pode ajudar especialmente na fase lutea quando a performance tende a cair\n- **Proteina whey/vegetal (20-30g/dose)**: completar a meta proteica diaria. Essencial na fase lutea quando o catabolismo aumenta\n- **Vitamina D3 (1000-2000 UI/dia)**: a maioria das mulheres brasileiras tem deficiencia. Essencial para saude ossea e imunidade\n- **Omega-3 (1-3g EPA+DHA/dia)**: anti-inflamatorio, melhora perfil lipidico, pode reduzir dismenorreia\n\n### Suplementos com evidencia moderada\n- **Ferro**: apenas se diagnosticada deficiencia por exame de sangue. Mulheres com menstruacao abundante tem maior risco\n- **Magnesio (200-400mg/dia)**: pode reduzir caimbras, melhorar sono e aliviar TPM. Glicinato e a melhor forma\n- **Zinco (15-30mg/dia)**: importante para imunidade e cicatrizacao. Deficiencia e comum em veganas\n- **Ashwagandha (300-600mg/dia)**: adaptogeno com evidencia para reducao de cortisol e melhora de forca\n\n### Suplementos sem evidencia suficiente\n- BCAAs isolados (desnecessarios se proteina total e adequada)\n- Colageno para performance (evidencia fraca)\n- Multivitaminicos genericos (prefira suplementar deficiencias especificas)\n\n### Cuidados\n- Sempre faca exames antes de suplementar ferro, vitamina D e zinco\n- Interacao medicamentosa: informe seu medico sobre suplementos\n- Qualidade importa: busque selos de terceiros (NSF, Informed Sport)\n\n### Referencia\nMaughan RJ et al. IOC consensus statement: dietary supplements and the high-performance athlete. Br J Sports Med. 2018;52(7):439-455. Smith-Ryan AE et al. Nutritional considerations and strategies for female-specific athletic performance. Sports Med. 2021;51(Suppl 1):43-60.`,
    categorySlug: 'nutricao',
    cyclePhase: 'all',
  },
  {
    title: 'Como interpretar HRV para otimizar seu treino',
    summary: 'A variabilidade da frequencia cardiaca (HRV) e uma janela para seu sistema nervoso. Aprenda a usa-la.',
    body: `## HRV: seu indicador de prontidao\n\nA Variabilidade da Frequencia Cardiaca (HRV) mede a variacao do intervalo entre batimentos cardiacos. Uma HRV alta indica que o sistema nervoso parasimpatico (recuperacao) esta dominante, enquanto uma HRV baixa sugere estresse ou fadiga acumulada.\n\n### O que medir\n- **RMSSD**: metrica mais comum, mede variabilidade entre batimentos consecutivos\n- **Baseline pessoal**: sua media dos ultimos 30 dias. Nao compare com outras pessoas\n- **Tendencia**: mais importante que valores absolutos. Queda progressiva = overreaching\n\n### HRV e ciclo menstrual\n- **Fase folicular**: HRV tende a ser mais alta (parasimpatico dominante). Boa prontidao para treinos intensos\n- **Ovulacao**: pico ou queda rapida depende do individuo\n- **Fase lutea**: HRV tende a cair naturalmente (simpatico mais ativo). Nao interprete como overtraining\n- **Menstrual**: HRV pode flutuar. Contextualize com sintomas\n\n### Como usar na pratica\n- **HRV acima do baseline**: sinal verde para treino intenso (HIIT, forca pesada)\n- **HRV na media**: treino moderado conforme planejado\n- **HRV abaixo do baseline**: reduzir volume/intensidade, priorizar recuperacao\n- **HRV muito abaixo (>10% queda)**: dia de recuperacao ativa ou descanso total\n\n### Dicas de medicao\n- Medir ao acordar, deitada, por 1-3 minutos\n- Usar cinta toracica ou sensor optico de qualidade (Apple Watch, Whoop, Oura)\n- Medir todos os dias no mesmo horario\n- Registrar contexto: sono, estresse, fase do ciclo\n\n### Ferramentas recomendadas\n- **HRV4Training**: app com protocolo validado cientificamente\n- **Whoop**: monitoramento continuo com insights de recuperacao\n- **Oura Ring**: medicao noturna automatica\n- **Apple Watch**: HRV disponivel no app Saude\n\n### Referencia\nPlews DJ et al. Training adaptation and heart rate variability in elite endurance athletes. Int J Sports Physiol Perform. 2013;8(6):688-694. Trevisan C et al. Heart rate variability across the menstrual cycle: a systematic review. Auton Neurosci. 2023;247:103090.`,
    categorySlug: 'geral',
    cyclePhase: 'all',
  },
  {
    title: 'Mindfulness e reducao de cortisol: praticas para a mulher ativa',
    summary: 'O estresse cronico prejudica performance, ciclo menstrual e composicao corporal. Mindfulness e uma solucao baseada em evidencias.',
    body: `## Mindfulness e cortisol\n\nO cortisol e o principal hormonio do estresse. Em niveis cronicamente elevados, causa catabolismo muscular, acumulo de gordura visceral, insonia, irregularidade menstrual e supressao imunologica. Mulheres ativas frequentemente subestimam o impacto do estresse mental no treino.\n\n### Como o cortisol afeta a mulher ativa\n- **Ciclo menstrual**: cortisol cronico pode causar amenorreia hipotalamica\n- **Composicao corporal**: favorece acumulo de gordura abdominal\n- **Recuperacao**: prejudica a sintese proteica muscular\n- **Sono**: cortisol alto a noite impede o sono profundo\n- **Imunidade**: aumenta risco de infeccoes respiratorias\n\n### Praticas de mindfulness com evidencia\n- **Meditacao guiada (10-20 min/dia)**: reduz cortisol em 23% em 8 semanas segundo estudos com MBSR\n- **Body scan**: varredura corporal deitada, 15 minutos. Otima antes de dormir\n- **Respiracao 4-7-8**: inspire 4s, segure 7s, expire 8s. 4 ciclos. Ativa o parasimpatico imediatamente\n- **Journaling**: escrever 10 minutos sobre gratidao ou preocupacoes reduz ruminacao mental\n- **Yoga nidra**: "sono yoguico", 20-30 minutos equivalem a 2h de sono em termos de restauracao\n\n### Protocolo semanal sugerido\n- **Segunda a sexta**: 10 min de meditacao matinal + respiracao 4-7-8 antes de dormir\n- **Pos-treino intenso**: 5 min de body scan para acelerar transicao para parasimpatico\n- **Domingo**: sessao longa de yoga nidra ou meditacao de 30 min\n\n### Integracao com ciclo\n- **Fase lutea**: priorize mindfulness - cortisol ja esta naturalmente mais alto\n- **Menstrual**: body scan e yin yoga para acolhimento\n- **Folicular**: meditacao de visualizacao e intencao para a fase ativa\n\n### Referencia\nTurakitwanakan W et al. Effects of mindfulness meditation on serum cortisol of medical students. J Med Assoc Thai. 2013;96 Suppl 1:S90-5. Pascoe MC et al. Mindfulness mediates the physiological markers of stress: systematic review and meta-analysis. J Psychiatr Res. 2017;95:156-178.`,
    categorySlug: 'saude-mental',
    cyclePhase: 'all',
  },
  {
    title: 'Ferro e performance: quando suplementar',
    summary: 'A deficiencia de ferro e a carencia nutricional mais comum em mulheres ativas. Saiba identificar e tratar.',
    body: `## Ferro e performance feminina\n\nO ferro e essencial para o transporte de oxigenio (hemoglobina), armazenamento de oxigenio muscular (mioglobina) e producao de energia (citocromos). Mulheres em idade reprodutiva perdem ferro mensalmente pela menstruacao, tornando a deficiencia extremamente comum.\n\n### Prevalencia\n- **15-35% das mulheres ativas** tem deficiencia de ferro (ferritina < 30 ng/mL)\n- **5-11%** tem anemia franca (hemoglobina < 12 g/dL)\n- Corredoras de longa distancia e vegetarianas tem risco ainda maior\n- A perda menstrual media e 1mg de ferro/dia durante o sangramento\n\n### Sintomas de deficiencia\n- Fadiga desproporcional ao esforco\n- Queda de performance sem explicacao\n- Frequencia cardiaca elevada em repouso\n- Palidez, unhas frageis, queda de cabelo\n- Dificuldade de concentracao\n- Recuperacao prolongada entre sessoes de treino\n\n### Exames essenciais\n- **Ferritina serica**: ideal > 50 ng/mL para atletas (nao apenas > 12)\n- **Hemoglobina**: ideal > 13 g/dL para performance\n- **Saturacao de transferrina**: ideal 20-45%\n- **Ferro serico**: avaliar em conjunto com ferritina\n- Solicitar exames a cada 3-6 meses se ativa e menstruando\n\n### Fontes alimentares\n- **Ferro heme (melhor absorcao)**: carne vermelha, figado, frango, peixe\n- **Ferro nao-heme**: feijao, lentilha, tofu, espinafre, brocolis\n- **Potencializadores**: vitamina C junto a refeicao aumenta absorcao em ate 6x\n- **Inibidores**: cafe, cha, laticinionios na mesma refeicao reduzem absorcao\n\n### Quando suplementar\n- Ferritina < 30 ng/mL: suplementacao oral (sulfato ferroso, bisglicinato)\n- Ferritina < 15 ng/mL com sintomas: considerar ferro endovenoso\n- **Dose tipica oral**: 60-100mg de ferro elementar, em dias alternados (melhor absorcao)\n- Tomar com vitamina C, longe de cafe e laticinionios\n- Reavaliar ferritina apos 3 meses\n\n### Referencia\nPeeling P et al. Athletic induced iron deficiency: new insights into the role of inflammation, cytokines and hormones. Eur J Appl Physiol. 2008;103(4):381-391. McClung JP et al. Iron status and the female athlete. J Trace Elem Med Biol. 2014;28(4):388-392.`,
    categorySlug: 'nutricao',
    cyclePhase: 'menstrual',
  },
];

export const SEED_CATEGORIES = [
  { name: 'Ciclo menstrual', slug: 'ciclo' },
  { name: 'Treino', slug: 'treino' },
  { name: 'Nutricao', slug: 'nutricao' },
  { name: 'Saude mental', slug: 'saude-mental' },
  { name: 'Geral', slug: 'geral' },
];
