export const SEED_RECIPES = [
  // MENSTRUAL (2 receitas)
  {
    title: 'Bowl de aveia com banana e cacau',
    summary: 'Comfort food funcional rica em magnesio e ferro para a fase menstrual.',
    instructions: '1. Cozinhe a aveia em fogo medio com o leite por 5 minutos, mexendo.\n2. Adicione a banana amassada e misture.\n3. Transfira para uma tigela e cubra com cacau, mel e castanhas.\n4. Polvilhe a canela por cima.',
    ingredients: [
      { name: 'Aveia em flocos', quantity: '60', unit: 'g' },
      { name: 'Leite vegetal', quantity: '200', unit: 'ml' },
      { name: 'Banana madura', quantity: '1', unit: 'un' },
      { name: 'Cacau em po', quantity: '1', unit: 'colher de sopa' },
      { name: 'Mel', quantity: '1', unit: 'colher de cha' },
      { name: 'Castanha de caju', quantity: '20', unit: 'g' },
      { name: 'Canela em po', quantity: '1', unit: 'pitada' },
    ],
    macros: { calories: 420, protein: 12, carbs: 62, fat: 15, fiber: 8 },
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    servings: 1,
    dietaryRestrictions: ['sem gluten', 'vegana'],
    cyclePhase: 'menstrual',
    categorySlug: 'nutricao',
  },
  {
    title: 'Sopa de lentilha com espinafre',
    summary: 'Rica em ferro e anti-inflamatoria. Ideal para repor nutrientes na menstruacao.',
    instructions: '1. Refogue o alho e a cebola no azeite por 2 minutos.\n2. Adicione a lentilha lavada, o tomate picado e a agua.\n3. Cozinhe por 20 minutos em fogo medio.\n4. Adicione o espinafre e o curcuma nos ultimos 3 minutos.\n5. Tempere com sal, pimenta e suco de limao.',
    ingredients: [
      { name: 'Lentilha', quantity: '150', unit: 'g' },
      { name: 'Espinafre', quantity: '100', unit: 'g' },
      { name: 'Tomate', quantity: '2', unit: 'un' },
      { name: 'Cebola', quantity: '1', unit: 'un' },
      { name: 'Alho', quantity: '2', unit: 'dentes' },
      { name: 'Curcuma', quantity: '1', unit: 'colher de cha' },
      { name: 'Azeite', quantity: '1', unit: 'colher de sopa' },
      { name: 'Agua', quantity: '500', unit: 'ml' },
      { name: 'Limao', quantity: '1/2', unit: 'un' },
    ],
    macros: { calories: 380, protein: 24, carbs: 52, fat: 8, fiber: 16 },
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 2,
    dietaryRestrictions: ['sem gluten', 'vegana'],
    cyclePhase: 'menstrual',
    categorySlug: 'nutricao',
  },

  // FOLLICULAR (2 receitas)
  {
    title: 'Frango grelhado com batata doce e brocolis',
    summary: 'Refeicao rica em proteina e carboidratos complexos para sustentar treinos intensos na fase folicular.',
    instructions: '1. Tempere o frango com alho, limao, sal e pimenta. Marine por 15 minutos.\n2. Corte a batata doce em cubos e tempere com azeite e alecrim.\n3. Asse a batata doce a 200C por 25 minutos.\n4. Grelhe o frango em frigideira quente por 6 minutos de cada lado.\n5. Cozinhe o brocolis no vapor por 4 minutos.\n6. Monte o prato e finalize com azeite.',
    ingredients: [
      { name: 'Peito de frango', quantity: '200', unit: 'g' },
      { name: 'Batata doce', quantity: '200', unit: 'g' },
      { name: 'Brocolis', quantity: '150', unit: 'g' },
      { name: 'Alho', quantity: '2', unit: 'dentes' },
      { name: 'Limao', quantity: '1/2', unit: 'un' },
      { name: 'Azeite', quantity: '1', unit: 'colher de sopa' },
      { name: 'Alecrim', quantity: '1', unit: 'ramo' },
    ],
    macros: { calories: 520, protein: 45, carbs: 48, fat: 14, fiber: 8 },
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    servings: 1,
    dietaryRestrictions: ['sem gluten', 'sem lactose'],
    cyclePhase: 'follicular',
    categorySlug: 'nutricao',
  },
  {
    title: 'Smoothie proteico de frutas vermelhas',
    summary: 'Pre-treino ou pos-treino ideal na fase folicular. Rico em antioxidantes e proteina.',
    instructions: '1. Adicione todos os ingredientes no liquidificador.\n2. Bata por 1 minuto ate ficar homogeneo.\n3. Sirva imediatamente.',
    ingredients: [
      { name: 'Whey protein (baunilha)', quantity: '30', unit: 'g' },
      { name: 'Morango congelado', quantity: '100', unit: 'g' },
      { name: 'Mirtilo congelado', quantity: '50', unit: 'g' },
      { name: 'Banana', quantity: '1/2', unit: 'un' },
      { name: 'Leite vegetal', quantity: '250', unit: 'ml' },
      { name: 'Semente de chia', quantity: '1', unit: 'colher de sopa' },
    ],
    macros: { calories: 340, protein: 30, carbs: 40, fat: 6, fiber: 7 },
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    dietaryRestrictions: ['sem gluten'],
    cyclePhase: 'follicular',
    categorySlug: 'nutricao',
  },

  // OVULATORY (2 receitas)
  {
    title: 'Salmao com quinoa e aspargos',
    summary: 'Refeicao de alta performance com omega-3 e proteina completa para o pico de energia ovulatorio.',
    instructions: '1. Cozinhe a quinoa conforme instrucoes da embalagem (15 min).\n2. Tempere o salmao com sal, pimenta e suco de limao.\n3. Grelhe o salmao em frigideira quente com azeite por 4 minutos de cada lado.\n4. Grelhe os aspargos na mesma frigideira por 3 minutos.\n5. Monte o prato: base de quinoa, salmao por cima e aspargos ao lado.\n6. Finalize com azeite e sementes de gergelim.',
    ingredients: [
      { name: 'File de salmao', quantity: '180', unit: 'g' },
      { name: 'Quinoa', quantity: '80', unit: 'g' },
      { name: 'Aspargos', quantity: '100', unit: 'g' },
      { name: 'Limao', quantity: '1/2', unit: 'un' },
      { name: 'Azeite', quantity: '1', unit: 'colher de sopa' },
      { name: 'Gergelim', quantity: '1', unit: 'colher de cha' },
    ],
    macros: { calories: 580, protein: 42, carbs: 44, fat: 24, fiber: 6 },
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 1,
    dietaryRestrictions: ['sem gluten', 'sem lactose'],
    cyclePhase: 'ovulatory',
    categorySlug: 'nutricao',
  },
  {
    title: 'Acai bowl proteico',
    summary: 'Energia rapida com antioxidantes. Perfeito para o pico hormonal da ovulacao.',
    instructions: '1. Bata o acai congelado com a banana e um pouco de leite vegetal ate ficar cremoso.\n2. Transfira para uma tigela.\n3. Cubra com granola, fatias de morango, banana e pasta de amendoim.\n4. Polvilhe com coco ralado.',
    ingredients: [
      { name: 'Polpa de acai', quantity: '200', unit: 'g' },
      { name: 'Banana congelada', quantity: '1', unit: 'un' },
      { name: 'Leite vegetal', quantity: '50', unit: 'ml' },
      { name: 'Granola sem acucar', quantity: '30', unit: 'g' },
      { name: 'Morango', quantity: '50', unit: 'g' },
      { name: 'Pasta de amendoim', quantity: '1', unit: 'colher de sopa' },
      { name: 'Coco ralado', quantity: '1', unit: 'colher de sopa' },
    ],
    macros: { calories: 480, protein: 14, carbs: 68, fat: 18, fiber: 10 },
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 1,
    dietaryRestrictions: ['sem gluten', 'vegana'],
    cyclePhase: 'ovulatory',
    categorySlug: 'nutricao',
  },

  // LUTEAL (2 receitas)
  {
    title: 'Curry de grao de bico com leite de coco',
    summary: 'Anti-inflamatorio e rico em magnesio. Confort food saudavel para a fase lutea e TPM.',
    instructions: '1. Refogue a cebola e o alho no azeite por 3 minutos.\n2. Adicione o gengibre ralado, curry em po e curcuma. Mexa por 1 minuto.\n3. Adicione o grao de bico escorrido, o tomate picado e o leite de coco.\n4. Cozinhe em fogo medio por 15 minutos.\n5. Adicione o espinafre nos ultimos 2 minutos.\n6. Sirva com arroz integral.',
    ingredients: [
      { name: 'Grao de bico cozido', quantity: '240', unit: 'g' },
      { name: 'Leite de coco', quantity: '200', unit: 'ml' },
      { name: 'Tomate', quantity: '2', unit: 'un' },
      { name: 'Espinafre', quantity: '80', unit: 'g' },
      { name: 'Cebola', quantity: '1', unit: 'un' },
      { name: 'Alho', quantity: '2', unit: 'dentes' },
      { name: 'Gengibre', quantity: '1', unit: 'colher de cha' },
      { name: 'Curry em po', quantity: '1', unit: 'colher de sopa' },
      { name: 'Curcuma', quantity: '1/2', unit: 'colher de cha' },
      { name: 'Arroz integral', quantity: '80', unit: 'g' },
    ],
    macros: { calories: 520, protein: 20, carbs: 64, fat: 22, fiber: 14 },
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 2,
    dietaryRestrictions: ['sem gluten', 'vegana'],
    cyclePhase: 'luteal',
    categorySlug: 'nutricao',
  },
  {
    title: 'Chocolate quente com especiarias',
    summary: 'Bebida reconfortante com magnesio e propriedades anti-inflamatorias. Alivia TPM.',
    instructions: '1. Aqueca o leite em fogo medio.\n2. Adicione o cacau em po, a canela e o gengibre. Mexa bem.\n3. Quando estiver quente (nao ferver), adicione o mel.\n4. Sirva com uma pitada de canela extra por cima.',
    ingredients: [
      { name: 'Leite vegetal', quantity: '300', unit: 'ml' },
      { name: 'Cacau em po', quantity: '2', unit: 'colheres de sopa' },
      { name: 'Canela em po', quantity: '1/2', unit: 'colher de cha' },
      { name: 'Gengibre em po', quantity: '1/4', unit: 'colher de cha' },
      { name: 'Mel', quantity: '1', unit: 'colher de cha' },
    ],
    macros: { calories: 180, protein: 6, carbs: 28, fat: 6, fiber: 4 },
    prepTimeMinutes: 2,
    cookTimeMinutes: 5,
    servings: 1,
    dietaryRestrictions: ['sem gluten', 'sem lactose'],
    cyclePhase: 'luteal',
    categorySlug: 'nutricao',
  },
];
